_prefs: 
  mapid: enf.522e1931
  saveCenter: false
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 15.293
  - 50.8476
  - 4
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: Amtrak Northeast Regional speeds
source: "mapbox:///mapbox.mapbox-streets-v5,enf.adrvygb9,enf.gcvdkj4i"
styles: 
  - style.mss
  - labels.mss
  - roads.mss
template: ''
